basePath: /api/v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.ApiKey:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      value:
        type: string
    type: object
  models.PlainProject:
    properties:
      description:
        description: |-
          Description of the project
          Required: false
        type: string
      id:
        description: |-
          The id/slug for the project
          Required: true
          Min length: 1
        minLength: 1
        type: string
      image:
        description: |-
          Image of the project
          Required: false
        items:
          type: integer
        type: array
      name:
        description: |-
          Name of the project
          Required: false
        type: string
    required:
    - id
    type: object
  models.ProgressItem:
    properties:
      completedAt:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      eid:
        type: string
      id:
        type: integer
      state:
        type: string
      updatedAt:
        type: string
    type: object
  models.Project:
    properties:
      apiKeys:
        items:
          $ref: '#/definitions/models.ApiKey'
        type: array
      created_at:
        type: string
      description:
        description: |-
          Description of the project
          Required: false
        type: string
      id:
        description: |-
          The id/slug for the project
          Required: true
          Min length: 1
        minLength: 1
        type: string
      image:
        description: |-
          Image of the project
          Required: false
        items:
          type: integer
        type: array
      name:
        description: |-
          Name of the project
          Required: false
        type: string
      progressItems:
        items:
          $ref: '#/definitions/models.ProgressItem'
        type: array
      updated_at:
        type: string
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
    required:
    - id
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      kratosID:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:5454
info:
  contact:
    email: support@electratype.com
    name: API support and issue management
    url: https://electratype.com
  description: This a progress management system API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: JailBird API
  version: "1.0"
paths:
  /projects:
    get:
      consumes:
      - application/json
      description: Returns array of all projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Project'
            type: array
      summary: Return all projects
      tags:
      - project
    post:
      consumes:
      - application/json
      parameters:
      - description: Project definition
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.PlainProject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create new project
      tags:
      - project
  /projects/{id}:
    delete:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Delete project
      tags:
      - project
swagger: "2.0"
